#!/usr/bin/env bash
# This script displays running processes with columns: USER, STARTED, CMD using correct format

ps -eo user,lstart,cmd --no-headers | awk '{printf "%-8s %-8s %s\n", $1, $4":"$5":"$6, substr($0, index($0,$8))}'
