#!/usr/bin/env bash
# Bash script that displays “Best School” 10 times, for the 9th iteration script should display “Best School” and then, on a new line, display “Hi”.
count=1
while [ $count -le 10 ]
do
	echo "Best School"
  if [ $count == 9 ]; then
		echo "Hi"
	fi
	((count++))
done
