#!/usr/bin/env bash
#!/usr/bin/env bash
# 4 Bad Luck, 8 Is Your Chance
count=1
while [ $count -le 10 ]
do
	if [ $count == 4 ]; then
		echo "bad luck"
	elif [ $count == 8 ]; then
		echo "good luck"
  else
		echo "Best School"
	fi
	((count++))
done
